name: AutoPost to Facebook  # Name of your workflow
on:  # When the workflow should run
  schedule:
    - cron: '0 12 * * *'  # Runs daily at 12 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  autopost:  # Job ID
    runs-on: ubuntu-latest  # OS for the virtual machine

    steps:
      # Step 1: Check out your repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the Python script with secrets
      - name: Post to Facebook
        env:
          FB_PAGE_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}  # From GitHub Secrets
          FB_PAGE_ID: ${{ secrets.FB_PAGE_ID }}        # From GitHub Secrets
        run: python fb_autopost.py
