name: Facebook Auto-Poster
on:
  workflow_dispatch:  # Allow manual runs
  schedule:
    - cron: '0 8 * * *'  # 8 AM daily

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Run Post
        env:
          FB_TOKEN: ${{ secrets.FB_TOKEN }}
          PAGE_ID: ${{ secrets.PAGE_ID }}
        run: python fb_autopost.py
